### ISSUE TITLE
ModuleNotFoundError  No module named 'urdf_tutorial.state_publisher'

### ISSUE THREAD

**Issue by timf1** [benbongalon/ros2-migration#6]
Hi,

thanks for this tutorial.

I downloaded the package from repository, without changing nothing.  But I get an error on "ros2 launch urdf_tutorial demo.launch.py"

if you have an idea. 

[robot_state_publisher-1] [INFO] [1635090350.373655489] [robot_state_publisher]: got segment rod
[state_publisher-2] Traceback (most recent call last):
[state_publisher-2]   File "/home/tim/ros2_foxy/install/urdf_tutorial/lib/urdf_tutorial/state_publisher", line 11, in <module>
[state_publisher-2]     load_entry_point('urdf-tutorial', 'console_scripts', 'state_publisher')()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
[state_publisher-2]     return get_distribution(dist).load_entry_point(group, name)
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
[state_publisher-2]     return ep.load()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
[state_publisher-2]     return self.resolve()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
[state_publisher-2]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[state_publisher-2] ModuleNotFoundError: No module named 'urdf_tutorial.state_publisher'
[ERROR] [state_publisher-2]: process has died [pid 25782, exit code 1, cmd '/home/tim/ros2_foxy/install/urdf_tutorial/lib/urdf_tutorial/state_publisher --ros-args -r __node:=state_publisher'].

Thanks

**Comment by carlosfloar** [comment]
hello, I have the same problem, I download the repository, I follow the instructions in the tutorial and the error is the same, can someone help us? 

$ colcon build --symlink-install --packages-select urdf_tutorial
Starting >>> urdf_tutorial
Finished <<< urdf_tutorial [0.85s]          

Summary: 1 package finished [0.98s]

$ source install/setup.bash 
$ ros2 launch urdf_tutorial demo.launch.py

[INFO] [launch]: All log files can be found below /home/carlos/.ros/log/2021-10-29-18-40-13-483647-inspiron-14-3467-13129
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [13131]
[INFO] [state_publisher-2]: process started with pid [13133]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link leg1 had 0 children
[robot_state_publisher-1] Link leg2 had 0 children
[robot_state_publisher-1] Link body had 1 children
[robot_state_publisher-1] Link head had 1 children
[robot_state_publisher-1] Link rod had 1 children
[robot_state_publisher-1] Link box had 0 children
[robot_state_publisher-1] [INFO] [1635550813.612084368] [robot_state_publisher]: got segment axis
[robot_state_publisher-1] [INFO] [1635550813.612185727] [robot_state_publisher]: got segment body
[robot_state_publisher-1] [INFO] [1635550813.612197492] [robot_state_publisher]: got segment box
[robot_state_publisher-1] [INFO] [1635550813.612203625] [robot_state_publisher]: got segment head
[robot_state_publisher-1] [INFO] [1635550813.612209184] [robot_state_publisher]: got segment leg1
[robot_state_publisher-1] [INFO] [1635550813.612215047] [robot_state_publisher]: got segment leg2
[robot_state_publisher-1] [INFO] [1635550813.612220414] [robot_state_publisher]: got segment rod
[state_publisher-2] Traceback (most recent call last):
[state_publisher-2]   File "/home/carlos/dev_ws/install/urdf_tutorial/lib/urdf_tutorial/state_publisher", line 11, in <module>
[state_publisher-2]     load_entry_point('urdf-tutorial', 'console_scripts', 'state_publisher')()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[state_publisher-2]     return get_distribution(dist).load_entry_point(group, name)
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[state_publisher-2]     return ep.load()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[state_publisher-2]     return self.resolve()
[state_publisher-2]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[state_publisher-2]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[state_publisher-2] ModuleNotFoundError: No module named 'urdf_tutorial.state_publisher'
[ERROR] [state_publisher-2]: process has died [pid 13133, exit code 1, cmd '/home/carlos/dev_ws/install/urdf_tutorial/lib/urdf_tutorial/state_publisher --ros-args -r __node:=state_publisher'].

**Comment by benbongalon** [comment]
Hi Carlos,
What OS version and ROS version are you using?

**Comment by Danendra10** [comment]
Hi im facing the same issue

environment: 
ubuntu 22
ros humble

In my colcon build i got this warning error

/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(


in another issue they say to run this pip cmd

```pip3 install setuptools==60.7.0```

But i still got that error

And when I run it i got this eror

```bash
[state_publisher-2] Traceback (most recent call last):
[state_publisher-2]   File "/home/clevero/second_ros2_ws/install/urdf_tutorial_r2d2/lib/urdf_tutorial_r2d2/state_publisher", line 33, in <module>
[state_publisher-2]     sys.exit(load_entry_point('urdf-tutorial-r2d2', 'console_scripts', 'state_publisher')())
[state_publisher-2]   File "/home/clevero/second_ros2_ws/install/urdf_tutorial_r2d2/lib/urdf_tutorial_r2d2/state_publisher", line 25, in importlib_load_entry_point
[state_publisher-2]     return next(matches).load()
[state_publisher-2]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[state_publisher-2]     module = import_module(match.group('module'))
[state_publisher-2]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[state_publisher-2]     return _bootstrap._gcd_import(name[level:], package, level)
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[state_publisher-2]   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
[state_publisher-2] ModuleNotFoundError: No module named 'urdf_tutorial_r2d2'
[ERROR] [state_publisher-2]: process has died [pid 32542, exit code 1, cmd '/home/clevero/second_ros2_ws/install/urdf_tutorial_r2d2/lib/urdf_tutorial_r2d2/state_publisher --ros-args -r __node:=state_publisher'].
```
